global using Autofac;
global using Eum.EventBus;
global using Eum.EventBus.Core;
global using Eum.Module.Board;
global using Eum.Module.Board.Core.EventHandlers;
global using Eum.Module.Feelanet;
global using Eum.Shared.Common.Events;
global using Eum.Shared.Common.Extentions;
global using Serilog;
