global using Autofac;
global using Eum.Module.Board.Core.Commands.Article;
global using Eum.Module.Board.Shared.Interface.Queries;
global using Eum.Module.Board.Shared.Models.QueryViewModels;
global using Eum.Module.Board.Shared.Models.RequestModels;
global using Eum.Shared.Common.Bases;
global using Eum.Shared.Common.Extentions;
global using MediatR;
global using Microsoft.AspNetCore.Mvc;
